### ISSUE TITLE
Rojo session terminates in Studio when a new node is added to default.project.json

### ISSUE THREAD

**Issue by Integern** [rojo-rbx/vscode-rojo#18]
When you add a new node in default.project.json (via 'Rojo: Sync from here..', I haven't checked what happens when you edit the file directly)

VSCode Terminal
```
Project configuration changed, reloading Rojo.
Rojo server listening on port 34872
```

ROBLOX Studio Output
```
17:49:42.880 - [Rojo-Warn] Rojo session terminated because of an error:
17:49:42.880 - [Rojo-Warn] Unknown error: HttpError: NetFail
```

It connects back fine by clicking 'Connect' on the Rojo ROBLOX Plugin widget, but is annoying when testing and adding new files!

**Comment by evaera** [comment]
As LPG said, this is actually intentional. I think you would need to reload it manually to see your changes anyways, so it doesn't really make sense to me for this to not be the case.
