### ISSUE TITLE
Rojo build format config

### ISSUE THREAD

**Issue by Xuleos** [rojo-rbx/vscode-rojo#23]
Rbx-dom currently has pretty weak support for Roblox's binary format (rbxl and rbxm). It would be super sweet if there was a way to configure vscode-rojo to use the xml format ( rbxlx and rbxmx ) when building.

**Comment by evaera** [comment]
Thanks for bringing this up, the default should probably be XML anyways.

**Comment by lukechatton** [comment]
Any progress on this?

**Comment by evaera** [comment]
Haven't done anything on it yet. Will probably go out in the next major update I do. If you want to submit a PR you are welcome to :)
