### ISSUE TITLE
Allow serving from different project files

### ISSUE THREAD

**Issue by evaera** [rojo-rbx/vscode-rojo#33]
- extension setting for what project names to use
- command palette option to serve from a specific file as a one-off. Make a pop-up and ask if user would like to make it the default
- preconfigured priority list to check for, like `test.project.json`, `serve.project.json`, `default.project.json` for serve mode, and `build.project.json`, ... for build mode

**Comment by general-adhoc** [comment]
This would be incredibly useful if implemented at some point!

**Comment by B-Ricey763** [comment]
I would absolutely love to see this! The extension right now is super good, with most of the features of Rojo, but allowing other `.project.json`  files would be absolutely amazing!
