### ISSUE TITLE
Falling back to installed version if Github goes down

### ISSUE THREAD

**Issue by mkargus** [rojo-rbx/vscode-rojo#56]
The extension will get stuck on "Downloading Rojo..." and will not fallback to the already installed version if [Github has issues](https://www.githubstatus.com/incidents/r5qrpp2f5fc0). 

Without a fallback in this case, it will throw `Cannot read 'property' of find of undefined` (#55) or HTTP status 500 errors. The extension will basically lock up until the user reload the windows.

**Comment by evaera** [comment]
This has been implemented in version 2 of the extension which is now the master branch
