### ISSUE TITLE
Respect foreman configuration for Rojo version

### ISSUE THREAD

**Issue by OverHash** [rojo-rbx/vscode-rojo#57]
Currently the vscode extension will use the "release branch" install from, with a "target version" as an override.

It would be beneficial if the vscode extension looked for a `foreman.toml` file and respects the configuration [foreman](https://github.com/Roblox/foreman) uses. This would make collaborators across a project all use the same version of Rojo.

**Comment by GlowingUmbreon** [comment]
VSCode does have something called workspace settings that achieves the same effect. If you go to VSCode settings and click the workspace tab and change the version there anyone who uses the repository using VSCode will automatically use those settings.

**Comment by evaera** [comment]
This has been implemented in version 2 of the extension which is now the master branch
