### ISSUE TITLE
Platform not supported warning under Arch linux

### ISSUE THREAD

**Issue by interpreterK** [rojo-rbx/vscode-rojo#63]
As the title says, any time i start up rojo (7.0.0) i get a warning saying "Couldn't install Rojo plugin: your platform is not supported" but the extension does work and connects to the localhost and the roblox studio rojo plugin can pick it up.
`uname -a`:
`Linux arch 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64 GNU/Linux`

Maybe consider having linux as a supported OS since grapejuice and wine can now run roblox and roblox studio on linux just like native

**Comment by cyrus01337** [comment]
Running on Ubuntu 20.0.4 and Rojo + Grapejuice work flawlessly, is there anything that still needs to be confirmed in order for Linux (or at the very least the following distros) to be considered supported?

**Comment by evaera** [comment]
Future development is being done in the v2 branch, which is not published yet. You can install it now if you want: https://github.com/rojo-rbx/vscode-rojo/releases/tag/2.0.0-alpha.0
