### ISSUE TITLE
vs code plugin not working in version 2+

### ISSUE THREAD

**Issue by Rae3504** [rojo-rbx/vscode-rojo#72]
The button on the bottom bar no longer appears and doing Rojo: Open Menu from the command palette throws an error.

![Screenshot 2022-08-13 at 12 46 46](https://user-images.githubusercontent.com/72041996/184493554-72252d82-1767-43c0-bf14-f6bc14598504.png)

Using rojo from the terminal still works fine though.
For now, I've reverted to the previous release (1.13.4) and it works fine.

**Comment by evaera** [comment]
Did you try restarting VS Code and trying again? This error is pretty weird. It says the command is not found, which means the extension isn't loaded. There isn't much we can do about that if our code isn't being loaded at all. Running a command from an extension in VSCode is supposed to automatically load it.

**Comment by Rae3504** [comment]
Yeah I mean I've tried everything, even reinstalled vsc. I did a bit of digging and I found this, hopefully this helps
![Screenshot 2022-08-13 at 19 38 56](https://user-images.githubusercontent.com/72041996/184506681-b54a47d3-c31f-4b86-a608-b7c2dba37d57.png)

**Comment by evaera** [comment]
So this is the latest version of VS Code?

**Comment by Rae3504** [comment]
My bad actually, I didn't realise my files were still being opened the older version I had on my pc not the version I just downloaded. It is working fine now in the newest version of vsc.
