### ISSUE TITLE
Suggestion: Add mouse free project building

### ISSUE THREAD

**Issue by BRUJOjr** [rojo-rbx/vscode-rojo#75]
As of the latest update, it is impossible to build a project without using your mouse which is very impractical. You could make it a separate button in the Rojo menu or add a command for it.

**Comment by evaera** [comment]
Hi, you can build the project without using the mouse by making use of the tab button. 

https://user-images.githubusercontent.com/2489210/187316399-f992010f-0916-4417-9bc5-219272e86627.mp4
