### ISSUE TITLE
initializing don't work

### ISSUE THREAD

**Issue by 1zHunter** [rojo-rbx/vscode-rojo#8]
every time i use the command "Rojo: initialize" it throw an error.
spawnSync c:\Users\me\.vscode\extensions\evaera.vscode-rojo-1.6.1\bin\rojo-v0.4.13.exe UNKNOWN

**Comment by beijibeijing** [comment]
I use Mac,and the version is rojo-v6.2.0.
"spawnSync /Users/userName/Library/Application Support/Code/User/globalStorage/evaera.vscode-rojo/rojo-v6.2.0 Unknown system error -88"
