### ISSUE TITLE
Renaming a file duplicates it

### ISSUE THREAD

**Issue by DeveloperAnonymous** [rojo-rbx/vscode-rojo#80]
Hello! When you rename a file in vscode, it duplicates it in roblox studio

**Comment by evaera** [comment]
This is probably because you have ignoreUnknownDescendants on. However, this is the wrong repo for issues like this. This is for the vscode extension. If you have questions like this, you should join the Roblox Open Source discord which is linked in the extension and ask in the rojo channel
